# Site settings
title: Cintia Higashi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a space for me and my stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cintiamh.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  cintiamh

# Build settings
markdown: kramdown
