# Site settings
title: Cintia Higashi
description: > # this means to ignore newlines until "baseurl:"
  Just another Web Developer that loves what she does.
  I am currently working as a Front End Software Engineer at Yahoo!, making cool ads for the Yahoo!'s home page and
  developing tools to make the everyday work easier.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cintiamh.github.io" # the base hostname & protocol for your site
twitter_username: panda_japa
github_username:  cintiamh

# Build settings
markdown: kramdown
